### ISSUE TITLE
undefined method `inner_text’ for nil:NilClass

### ISSUE THREAD

**Issue by gaebk02** [isy/miyabi#3]
[yomikatawa](https://yomikatawa.com/kanji/)ページが更新されることにより、
to_kanhiraメソッドが動かなくなりました。
メソッドの修正をお願いしたいです。

```
  def to_kanhira
    agent = Mechanize.new
    agent.get("https://yomikatawa.com/kanji/#{self}").search('#yomikata tbody tr td').first.inner_text
  end
```
上記でできると思います。

**Comment by IvanReyesO7** [comment]
@isy Hi, any plans to implement this #5 ?

**Comment by gemmaro** [comment]
Released as [v0.1.2][v].

[v]: https://rubygems.org/gems/miyabi/versions/0.1.2
